name: FMUBuild

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
    push:
        paths:
            - 'deps/src'
    pull_request:
        paths:
            - 'deps/src'
    workflow_dispatch:
    workflow_run:
        workflows: ["Docker"]
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: build
              uses: docker://ghcr.io/${{ github.repository }}
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: fmus
                path: deps/fmu.tar.gz

